FROM ruby:3.4.5

# Install dependencies
RUN apt-get update -qq && apt-get install -y \
  postgresql-client \
  build-essential \
  libpq-dev \
  nodejs \
  npm \
  && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Install gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy the main application
COPY . ./

# Expose port
EXPOSE 3001

# Start the server
CMD ["rails", "server", "-b", "0.0.0.0", "-p", "3001"]